version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: gestlab-db
    environment:
      POSTGRES_DB: gestlab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
